# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pingpong.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epingpong.proto\x12\x17net.serg.stubs.pingpong\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cPongResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2f\n\x0fPingPongService\x12S\n\x04ping\x12$.net.serg.stubs.pingpong.PingRequest\x1a%.net.serg.stubs.pingpong.PongResponseB\x1b\n\x17net.serg.stubs.pingpongP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pingpong_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027net.serg.stubs.pingpongP\001'
  _globals['_PINGREQUEST']._serialized_start=43
  _globals['_PINGREQUEST']._serialized_end=73
  _globals['_PONGRESPONSE']._serialized_start=75
  _globals['_PONGRESPONSE']._serialized_end=106
  _globals['_PINGPONGSERVICE']._serialized_start=108
  _globals['_PINGPONGSERVICE']._serialized_end=210
# @@protoc_insertion_point(module_scope)
